apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: kube-prom-stack-kube-prome-prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
      nodePort: 30090  # Choose a port between 30000-32767
