apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: springboot-servicemonitor
  namespace: monitoring          # place ServiceMonitor in monitoring where operator watches it
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: springboot-demo
  namespaceSelector:
    matchNames:
      - default                  # where your springboot service is; change if you used a different ns
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
